<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Destiny;

class DestinySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Destiny::truncate();

        Destiny::create([
            'description_es' => 'Perú o República del Perú es un país que se encuentra ubicado al oeste de América del Sur. Su nombre, en el idioma quechua y aimara, se pronuncia Piruw. Limita al norte con Ecuador y con Colombia, al sur con Chile, al este con Brasil y Bolivia y al oeste con el océano Pacífico. Perú posee una extensión total de 1.280.000 km2. Su capital es Lima y las ciudades principales junto con esta son: Cuzco, Callao, Arequipa, Trujillo y Chiclayo.<br><br> El país se encuentra divido en 24 departamentos y la provincia constitucional del Callao. Posee una población de 33 millones de personas, se trata de un país con una gran tradición inca que mantiene incluso en la actualidad ya que la mayoría de sus habitantes son descendientes de nativos. Posee una diversidad de climas, vegetación y fauna, lo que convierte a Perú en un país con un gran atractivo turístico.<br><br> El idioma principal es el español, aunque existen muchas lenguas nativas entre las que se destaca el quechua. Perú ha heredado una amplia cultura precolombina, específicamente del imperio Inca, convirtiéndose así en la cultura precolombina más rica de América.<br><br> Luego de la conquista española, muchas costumbres nativas se perdieron, sin embargo, otras tantas perduran incluso en la actualidad. Así, la cultura precolombina y la herencia del imperio inca se pueden ver en las comidas autóctonas, en la música y en la arquitectura.<br><br> En cuanto a sus características topográficas, Perú se puede clasificar en tres grandes tipos de relieve: Costa, Sierra y Selva.<br><br> La costa sur de Perú presenta un clima subtropical árido, temperaturas en promedio de 18º C y precipitaciones anuales que llegan apenas a 150 mm. Hacia el norte, la costa es más cálida, con un promedio de 24 º C y más precipitaciones, especialmente durante el verano.<br><br> En la zona de las sierras el clima es templado subhúmedo, con temperaturas de 20º C y precipitaciones que promedian entre los 500 y los 1200 mm anuales. Esta zona también presenta clima frío, con temperaturas hasta 12º C y posibles heladas durante invierno.<br><br> En la zona de la selva existen dos tipos de climas: semitropical húmedo en la zona alta de la selva con un promedio de 27º C, y tropical húmedo en la zona de la selva baja con temperaturas promedio de 27º C. En cuanto a sus recursos naturales, Perú posee gran cantidad de petróleo, gas, hierro, oro, zinc, cobre y plata. Estos recursos fueron declarados en la Constitución de 1993 como patrimonio del estado nacional. La moneda que utiliza Perú se llama “sol” y el único emisor de moneda es el banco central de reserva del Perú.',
            
            'description_en' => 'Peru, or the Republic of Peru, is a country situated to the west of South America. Its name is pronounced as "Piruw" in the Quechua and Aymara languages. It shares borders with Ecuador and Colombia to the north, Chile to the south, Brazil and Bolivia to the east, and the Pacific Ocean to the west. Peru covers a total area of 1,280,000 km². Its capital is Lima, and the major cities along with it are Cuzco, Callao, Arequipa, Trujillo, and Chiclayo.<br><br> The country is divided into 24 departments and the constitutional province of Callao. It has a population of 33 million people and holds a strong Inca tradition, which persists to this day, as the majority of its inhabitants are descendants of native people. It boasts a diversity of climates, vegetation, and fauna, which makes Peru a country of significant tourist allure.<br><br> The primary language is Spanish, although there are many native languages among which Quechua stands out. Peru has inherited a rich pre-Columbian culture, specifically from the Inca Empire, making it the most affluent pre-Columbian culture in the Americas.<br><br> After the Spanish conquest, many native customs were lost, yet many others have endured even to the present day. Thus, pre-Columbian culture and the legacy of the Inca Empire can be seen in traditional foods, music, and architecture.<br><br> Concerning its topographical features, Peru can be categorized into three main geographical regions: Coast, Highlands, and Jungle.<br><br>  The southern coast of Peru experiences a dry subtropical climate, with average temperatures around 18ºC and annual precipitation barely reaching 150 mm. Moving northward, the coast becomes warmer, with an average of 24ºC and increased rainfall, particularly during the summer.<br> In the highlands, the climate is temperate subhumid, with temperatures around 20ºC and annual rainfall ranging from 500 to 1200 mm. This region also has colder climates, with temperatures dropping to 12ºC and the possibility of frost during winter.<br><br> The jungle region exhibits two types of climates: semitropical humid in the higher jungle areas, with an average temperature of 27ºC, and tropical humid in the lower jungle regions, with average temperatures around 27ºC.<br><br> Regarding its natural resources, Peru possesses a significant amount of oil, gas, iron, gold, zinc, copper, and silver. These resources were declared as the national heritage in the 1993 Constitution.<br> The currency used in Peru is called the "sol," and the sole currency issuer is the Central Reserve Bank of Peru.'
        ]);
    }
}
